version: '3.10'

services:
  php-fpm: &php-fpm-container
    build: .docker/php/fpm
    env_file:
      - .env
    environment: &php-fpm-environment
      COMPOSE_FILE: ${COMPOSE_FILE}
      PROXY_HTTP_PORT: ${PROXY_HTTP_PORT}
      PROXY_HTTPS_PORT: ${PROXY_HTTPS_PORT}
      PHP_CS_FIXER_IGNORE_ENV: ${PHP_CS_FIXER_IGNORE_ENV}
      APP_RUNTIME: ${APP_RUNTIME}
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/root/.ssh:ro

  proxy:
    build: .docker/proxy
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html:ro
    env_file:
      - .env
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
