name: Build

on:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

  pull_request:
    types:
      - published
      - created
      - edited
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    name: PHP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.3"
        include:
          - php-version: "8.3"
            composer-options: "--profile"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: mbstring, intl, iconv, ctype
          coverage: xdebug
          tools: pecl, phpunit, composer
          ini-values: post_max_size=256M
    
      - name: Setup composer
        uses: ramsey/composer-install@v1
        with:
          composer-options: "${{ matrix.composer-options }}"
      
      - name: Validate composer files
        run: composer validate
      
      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer update --prefer-dist --no-progress

      - name: Execute unit tests
        run: bin/phpunit -c phpunit.xml.dist --testsuite=Functional
